### ISSUE TITLE
cannot safely debug.sethook

### ISSUE THREAD

**Issue by prorid3r** [defold/extension-lmprof#2]
hi! I experience the following error when trying to use this in defold:

ERROR:SCRIPT: lmprof/scripts/lmprof_helper.lua:27: cannot safely debug.sethook
stack traceback:
  [C]:-1: in function start
  lmprof/scripts/lmprof_helper.lua:27: in function start
  lmprof/scripts/lmprof.script:19: in function <lmprof/scripts/lmprof.script:16>

Windows 10.
Defold 1.6.1
https://github.com/defold/extension-lmprof/archive/refs/tags/1.2.1-vanilla-lua-5.1.zip

Any way i can overcome it?

**Comment by AGulev** [comment]
It happens because you run game using F5 (with debugger). It doesn't work this way.  Use cmd/ctrl+B

I'll add extra check in `lmprof_helper.lua`
